jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-8-jdk zip unzip
          pip3 install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ProductOCR-apk
          path: bin/*.apk
