name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python and dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install Buildozer and other required dependencies
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-8-jdk zip unzip
          pip install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Step 4: Configure Buildozer to run Android build
      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      # Step 5: Upload APK artifact to GitHub Actions
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: ProductOCR-apk
          path: bin/*.apk

